apiVersion: apps/v1
kind: Deployment
metadata:
  name: estockapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estockapi-deployment
  template:
    metadata:
      labels:
        app: estockapi-deployment
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: estock-api
          image: testacrdocker.azurecr.io/estock-api:latest
          imagePullPolicy: Always        
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: server=postgres-service;database=estockdb;User Id=SA;Password=pass@word1;Pooling=false
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: estockapi-service
spec:
  type: LoadBalancer
  selector:
    app: estockapi-deployment
  ports:
  - port: 80
