apiVersion: apps/v1
kind: Deployment
metadata:
  name: estockgetway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estockgetway-deployment
  template:
    metadata:
      labels:
        app: estockgetway-deployment
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: estock-getway
        image: testacrdocker.azurecr.io/estock-getway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: estockgetway-service
spec:
  selector:
    app: estockgetway-deployment
  ports:
  - port: 80
