apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  selector:
    matchLabels:
      app: estock
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: testacrdocker.azurecr.io/estock-api:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ConnectionStrings__DefaultConnection
            value: postgresdb://postgres-service:5432
          - name: ASPNETCORE_URLS
            value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: estock
    service: webapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapi
