version: '3.4'

services:
  estock.api:
    container_name: EstockApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "estockdb"
    ports:
      - "8000:80"

  estockdb:
    container_name: EstockDB
    image: postgres:latest
    restart: always
    environment: 
      - POSTGRES_USER=SA
      - POSTGRES_PASSWORD=pass@word1
    ports:
      - '5432:5432'

  estock.getway:
    container_name: EstockGetway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "estock.api"
    ports:
      - "8001:80"

