version: '3.4'

services:
  estock.api:
    image: ${DOCKER_REGISTRY-}estockapi
    build:
      context: .
      dockerfile: EStock.Api/Dockerfile

  estockdb:
    image: postgres:latest

  estock.getway:
    image: ${DOCKER_REGISTRY-}estockgetway
    build:
      context: .
      dockerfile: EStock.Getway/Dockerfile

