version: '3.4'

services:
  estock.getway:
    image: ${DOCKER_REGISTRY-}estock-getway
    build:
      context: .
      dockerfile: EStock.Getway/Dockerfile

  estock.api:
    image: ${DOCKER_REGISTRY-}estock-api
    build:
      context: .
      dockerfile: EStock.Api/Dockerfile

  estock.db:
    ports:
      - '5432:5432'
    container_name: estock-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin@123
    #volumes:
    #   - 'estock.db-volume:/var/lib/postgresql/data'
    image: 'postgres'
    #networks:
    #  - estock-network

