version: '3.4'

services:
  estock.getway:
    image: ${DOCKER_REGISTRY-}estock-getway
    build:
      context: .
      dockerfile: EStock.Getway/Dockerfile

  estock.api:
    image: ${DOCKER_REGISTRY-}estock-api
    build:
      context: .
      dockerfile: EStock.Api/Dockerfile
  
  estock.db:
    container_name: estock-postgres
    image: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=admin@123
    
